# Generated by Django 5.1.1 on 2024-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boletines',
            fields=[
                ('id_boletin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_boletin', models.CharField(max_length=100)),
                ('fecha_boletin', models.DateField(max_length=50)),
                ('tags_boletin', models.ManyToManyField(related_name='boletines', to='Interfaz.tag')),
            ],
        ),
    ]
