# Generated by Django 5.1.1 on 2024-10-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0002_boletin_delete_boletines'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='url_pdf',
            field=models.CharField(default='', max_length=255),
        ),
    ]
