# Generated by Django 5.1.1 on 2024-10-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0003_boletin_url_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletin',
            name='url_pdf',
            field=models.FileField(upload_to='PDF/'),
        ),
    ]
