# Generated by Django 5.1.1 on 2024-10-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0005_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('EquipoU3I', 'EquipoU3I'), ('Bibliotecólogo/a', 'Bibliotecólogo/a')], max_length=50),
        ),
    ]
