# Generated by Django 5.1.1 on 2024-10-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0006_alter_empleado_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('EquipoU3I', 'EquipoU3I'), ('Bibliotecologo/a', 'Bibliotecologo/a')], max_length=50),
        ),
    ]
