# Generated by Django 5.1.1 on 2024-10-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0007_alter_empleado_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuentesInfo',
            fields=[
                ('id_fuente', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('tags', models.ManyToManyField(to='Interfaz.tag')),
            ],
        ),
    ]
