# Generated by Django 5.1.1 on 2024-11-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0008_fuentesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuentesinfo',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='fuentesinfo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Desactivado', 'Desactivado')], default='Activo', max_length=12),
        ),
        migrations.AddField(
            model_name='fuentesinfo',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
