# Generated by Django 5.1.1 on 2024-11-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0010_alter_fuentesinfo_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBoletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='boletin',
            name='tags_boletin',
            field=models.ManyToManyField(to='Interfaz.tagboletin'),
        ),
        migrations.AlterField(
            model_name='fuentesinfo',
            name='tags',
            field=models.ManyToManyField(to='Interfaz.tagfuente'),
        ),
    ]
