# Generated by Django 5.1.4 on 2025-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0012_usuariolector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariolector',
            name='preferencias',
        ),
        migrations.AddField(
            model_name='usuariolector',
            name='preferenciasTags',
            field=models.ManyToManyField(to='Interfaz.tagboletin'),
        ),
    ]
