# Generated by Django 5.1.4 on 2025-05-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0013_remove_usuariolector_preferencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariolector',
            name='boletinesNuevos',
            field=models.ManyToManyField(blank=True, to='Interfaz.boletin'),
        ),
    ]
