# Generated by Django 5.1.4 on 2025-06-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0014_usuariolector_boletinesnuevos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletinBorrador',
            fields=[
                ('id_boletin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_boletin', models.CharField(max_length=100)),
                ('fecha_boletin', models.DateField()),
                ('url_pdf', models.FileField(upload_to='PDF/')),
                ('tags_boletin', models.ManyToManyField(to='Interfaz.tagboletin')),
            ],
        ),
    ]
