from django.urls import path
from . import views
from django.views.generic import RedirectView

urlpatterns = [
     path('', RedirectView.as_view(url='Inicio/', permanent=False)),
    path('Inicio/', views.Inicio, name='Inicio'),
    path('Boletines/', views.Boletines, name='Boletines'),
    path('SobreVIGIFIA/', views.Sobre_vigifia, name='Sobre_vigifia'),
    path('Contacto/', views.Contacto, name='Contacto'),
    path('Login/', views.Login_form, name='Login'),
    path('Register_usuario/', views.Register_usuario, name='Register_usuario'),
    path('LoginUsuario/', views.LoginUsuario, name='LoginUsuario'),
    path('Login_view/', views.Login_view, name='Login_view'),
    path('PanelDeControl/', views.PanelDeControl, name='PanelDeControl'),
    path('confirmar/<uidb64>/<token>/', views.confirm_registration, name='confirm_registration'),
    path('logout/', views.Logout_view, name='Logout'),
    path('FuentesBiblio/', views.FuentesBiblio, name='FuentesBiblio'),
    path('FuentesU3I/', views.FuentesU3I, name='FuentesU3I'),
    path('IngresarFuente/', views.IngresarFuente, name='IngresarFuente'),
    path('IngresoFuente/', views.IngresoFuente, name='IngresoFuente'),
    path('BorrarTagFuente/', views.BorrarTagFuente, name='BorrarTagFuente'),
    path('BorradoTagFuente/<nombre>/', views.BorradoTagFuente, name='BorradoTagFuente'),
    path('IngresarTagFuente/', views.IngresarTagFuente, name='IngresarTagFuente'),
    path('IngresoTagFuente/', views.IngresoTagFuente, name='IngresoTagFuente'),
    path('ModificarFuente/<id_fuente>/', views.ModificarFuente, name='ModificarFuente'),
    path('EditarFuente/<id_fuente>/', views.EditarFuente, name='EditarFuente'),
    path('Estadisticas/', views.Estadisticas, name='Estadisticas'),
    path('AccesoBiblio/', views.AccesoBiblio, name='AccesoBiblio'),
    path('TagsFuentes/', views.TagsFuentes, name='TagsFuentes'),
    path('BoletinBiblio', views.BoletinBiblio, name='BoletinBiblio'),
    path('SubirBoletinPublicado/', views.subir_boletin_publicado, name='subir_boletin_publicado'),
    path('CrearBoletinBorrador/', views.CrearBoletinBorrador, name='CrearBoletinBorrador'),
    path('EditarBoletinBorrador/', views.EditarBoletinBorrador, name='EditarBoletinBorrador'),
    path('BorrarBoletin/', views.BorrarBoletin, name='BorrarBoletin'),
    path('BorradoBoletin/<id_boletin>/', views.BorradoBoletin, name='BorradoBoletin'),
    path('suscribirTema/<nombreTema>/', views.suscribirTema, name='suscribirTema'),
    path('desuscribirTema/<nombreTema>/', views.desuscribirTema, name='desuscribirTema'),
]